export const TEXTS = {
  appName: 'In Paris',
  tagline: 'Ce soir à Paris',
  location: 'Paris, Île-de-France',
  dataSource: 'Que faire à Paris',
  today: "Aujourd'hui",
  pickDate: 'Choisir une date',
  allCategories: 'Tous',
  allDay: 'Journée',
  free: 'Gratuit',
  sortedByTime: 'Triés par horaire',
  loadingMore: 'Chargement…',
  loadMore: (remaining: number) => `Explorer les ${remaining} autres sorties`,
  eventCount: (total: number) => `${total} événement${total > 1 ? 's' : ''}`,
  price: {
    free: 'Gratuit',
    freeWithConditions: 'Gratuit sous condition',
    paid: 'Payant',
    unknown: 'Tarif non communiqué',
  },
  error: {
    eyebrow: 'Connexion interrompue',
    title: 'Impossible de charger les événements',
    message: 'Le service est momentanément indisponible. Réessayez dans un instant.',
    action: 'Réessayer',
  },
  empty: {
    eyebrow: 'Gazette du silence',
    title: 'Aucun événement ce jour',
    message: "La capitale s'accorde une respiration. Feuilletez les jours à venir ou changez de catégorie.",
    action: "Revenir à aujourd'hui",
  },
  map: {
    badge: (count: number) => `Carte interactive · ${count} lieux`,
    zoomIn: 'Agrandir',
    zoomOut: 'Réduire',
    recenter: 'Recentrer Paris',
    close: 'Fermer',
    details: 'Détails',
    copyAddress: "Copier l'adresse",
    copyCoordinates: 'Copier GPS',
    copied: 'Copié',
    showMap: 'Carte',
    showList: 'Liste',
  },
}
